apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-devsecops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-devsecops-api
  template:
    metadata:
      labels:
        app: mini-devsecops-api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: mini-devsecops-api
          image: mini-devsecops-api:latest
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: mini-devsecops-api-service
spec:
  selector:
    app: mini-devsecops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP