name: DevSecOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Docker image
        run: docker build -t mini-devsecops-api:latest .

      - name: Lint Kubernetes YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: deployment.yaml

            - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 0

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: mini-devsecops-api:latest
          format: table
          exit-code: 0

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.59.0/conftest_0.59.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.59.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run Conftest policy
        run: conftest test deployment.yaml --policy policy
